find seqs from EndBlocks
bandprotocol/relayer pull request #2
Opened 2021-04-02 07:38 UTC by songwongtp

find seqs in endblocks when seqs cannot be found in any txs (for bandchain endblock event)

2021-04-19 06:30 UTC, taobun requested changes

2021-04-19 06:30 UTC, taobun commented on relayer/naive-strategy.go
> +		// NOTE: search the given seq in endblock instead
?

2021-04-19 06:34 UTC, songwongtp commented on relayer/naive-strategy.go
> +		// NOTE: search the given seq in endblock instead
whoops. need to remove the comment

2021-04-19 06:39 UTC, taobun requested changes

2021-04-19 06:39 UTC, taobun commented on relayer/naive-strategy.go
> +		return nil, nil, fmt.Errorf("more than one relay msg found in tx query")
tx?

2021-04-19 07:22 UTC, songwongtp commented on relayer/naive-strategy.go
> +		// NOTE: search the given seq in endblock instead
see a11cd6f

2021-04-19 07:22 UTC, songwongtp commented on relayer/naive-strategy.go
> +		return nil, nil, fmt.Errorf("more than one relay msg found in tx query")
a11cd6f

2021-05-12 06:19 UTC, taobun approved these changes

2021-05-12 06:19 UTC, merged